name: HD Beauty Studio
favicon: null
layout_spectrum: 0.85645
typography_spectrum: 0.41083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#222627'
    - '#5a6467'
    - '#c3c7c9'
    - '#93999b'
  brandStrength: 0.9453733169939369
  lightness: 0.06586938467808068
  saturation: 0.6605994862038642
  rhythmicContrast: 0.6136673772707582
purpose: []
