name: HD Beauty Studio
favicon: null
layout_spectrum: 0.7067088149487972
typography_spectrum: 0.9310558040160686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9453733169939369
  lightness: 0.06586938467808068
  saturation: 0.6605994862038642
  rhythmicContrast: 0.6136673772707582
purpose: []
